# Generated by Django 3.0 on 2019-12-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50, verbose_name='book_name')),
                ('bprice', models.FloatField(verbose_name='book_price')),
                ('bauthor', models.CharField(max_length=50, verbose_name='book_author')),
                ('bremarks', models.TextField(max_length=50, verbose_name='book_remarks')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auther.Author')),
            ],
            options={
                'db_table': 'Book_Info',
            },
        ),
    ]
