# Generated by Django 3.0 on 2019-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50, verbose_name='author_name')),
                ('aage', models.IntegerField(verbose_name='author_age')),
                ('aexp', models.CharField(max_length=50, verbose_name='author_exp')),
                ('aemail', models.EmailField(max_length=50, verbose_name='author_email')),
            ],
            options={
                'db_table': 'Author_Info',
            },
        ),
    ]
